### ISSUE TITLE
when npm publish packages ? - roadmap

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#45]
There are some bugs. When they are resolved, the entire package will be released as npm.

- [x] [Docs](https://github.com/oku-ui/docs) code and publish `oku-ui.com`

Bugs

- [x] https://github.com/oku-ui/primitives/issues/69
- [x] https://github.com/oku-ui/primitives/issues/50
- [x] https://github.com/oku-ui/primitives/issues/52
- [x] https://github.com/oku-ui/primitives/issues/72
- [x] https://github.com/oku-ui/primitives/issues/103

this place will always be updated until it's done.

**Comment by productdevbook** [comment]
Check twitter publish: https://twitter.com/oku_ui/status/1659622892445810697
